export default function Home() {
    return (
        <div style={{ padding: "40px" }}>
            <h1>Generated App</h1>
            <p>This app was generated by AutoStack AI.</p>
            {/* AUTO-INJECT-COMPONENTS */}
        </div>
    );
}