"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import GenerationProgress from "./GenerationProgress";
import {
  Monitor, Code2, FolderTree, Terminal, GitBranch,
  RefreshCw, Globe, Smartphone, Tablet, ChevronRight,
  ChevronDown, File, Copy, Download, MessageSquare, Send,
  Archive, RotateCcw, GitCompare, AlertCircle, Loader2, Book
} from "lucide-react";

const TABS: { id: TabId; icon: React.ElementType; label: string }[] = [
  { id: "preview", icon: Monitor, label: "Preview" },
  { id: "code", icon: Code2, label: "Code" },
  { id: "files", icon: FolderTree, label: "Project" },
  { id: "docs", icon: Book, label: "Docs" },
  { id: "logs", icon: Terminal, label: "Logs" },
  { id: "versions", icon: GitBranch, label: "Versions" },
];

type TabId = "preview" | "code" | "files" | "docs" | "logs" | "versions" | "chat";

// ─── Preview Tab ────────────────────────────────────────────────────────────
const viewports = [
  { id: "desktop", icon: Monitor, w: "100%" },
  { id: "tablet", icon: Tablet, w: "768px" },
  { id: "mobile", icon: Smartphone, w: "390px" },
];

function PreviewTab({ app, isGenerating, onComplete }: { app: any, isGenerating: boolean, onComplete?: () => void }) {
  const [vp, setVp] = useState("desktop");
  const width = viewports.find((v) => v.id === vp)?.w ?? "100%";

  return (
    <div className="flex flex-col h-full">
      {/* Browser bar */}
      <div className="flex items-center gap-2 px-3 py-2 border-b border-white/6 bg-white/2 shrink-0">
        <div className="flex gap-1.5">
          <span className="w-2.5 h-2.5 rounded-full bg-red-500/60" />
          <span className="w-2.5 h-2.5 rounded-full bg-yellow-500/60" />
          <span className="text-[11px] text-slate-500 flex-1 ml-2 font-mono">localhost:3000</span>
        </div>
        <div className="flex items-center gap-1">
          {viewports.map(({ id, icon: Icon }) => (
            <button
              key={id}
              onClick={() => setVp(id)}
              className={`p-1.5 rounded-lg transition-all ${vp === id ? "bg-cyan-500/15 text-cyan-400" : "text-slate-600 hover:text-slate-300"}`}
            >
              <Icon size={13} />
            </button>
          ))}
        </div>
      </div>

      {/* Frame */}
      <div className="flex-1 overflow-auto bg-[#010410] flex justify-center p-4">
        <div
          className="h-full rounded-xl overflow-hidden border border-white/6 transition-all duration-500 shadow-2xl bg-[#020617]"
          style={{ width, minHeight: "400px" }}
        >
          {isGenerating ? (
            <GenerationProgress isGenerating={true} onComplete={onComplete || (() => {})} />
          ) : app?.previewLink ? (
            <iframe 
              src={app.previewLink} 
              className="w-full h-full border-none bg-white" 
              title="Preview"
            />
          ) : (
            <div className="h-full flex items-center justify-center text-center p-12">
               <div className="max-w-xs">
                <Monitor size={32} className="text-slate-700 mx-auto mb-4" />
                <p className="text-sm text-slate-500">Preview link will appear here after generation complete.</p>
               </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ─── Code Tab ───────────────────────────────────────────────────────────────
const mockCode = [
  { ln: 1, tokens: [{ t: "cmt", v: "// app/page.tsx — Generated by AutoStack AI" }] },
  { ln: 2, tokens: [] },
  { ln: 3, tokens: [{ t: "kw", v: "import" }, { t: "var", v: " React" }, { t: "kw", v: " from" }, { t: "str", v: " 'react'" }, { t: "pun", v: ";" }] },
  { ln: 4, tokens: [{ t: "kw", v: "import" }, { t: "pun", v: " { " }, { t: "fn", v: "useState" }, { t: "pun", v: ", " }, { t: "fn", v: "useEffect" }, { t: "pun", v: " }" }, { t: "kw", v: " from" }, { t: "str", v: " 'react'" }, { t: "pun", v: ";" }] },
  { ln: 5, tokens: [] },
  { ln: 6, tokens: [{ t: "kw", v: "export default function" }, { t: "fn", v: " Dashboard" }, { t: "pun", v: "() {" }] },
  { ln: 7, tokens: [{ t: "kw", v: "  const" }, { t: "pun", v: " [" }, { t: "var", v: "data" }, { t: "pun", v: ", " }, { t: "fn", v: "setData" }, { t: "pun", v: "] =" }, { t: "fn", v: " useState" }, { t: "pun", v: "<" }, { t: "typ", v: "any" }, { t: "pun", v: "[]>([]);" }] },
  { ln: 8, tokens: [] },
  { ln: 9, tokens: [{ t: "fn", v: "  useEffect" }, { t: "pun", v: "(() => {" }] },
  { ln: 10, tokens: [{ t: "cmt", v: "    // Fetch dashboard metrics" }] },
  { ln: 11, tokens: [{ t: "fn", v: "    fetch" }, { t: "pun", v: "(" }, { t: "str", v: "'/api/metrics'" }, { t: "pun", v: ")" }] },
  { ln: 12, tokens: [{ t: "pun", v: "      ." }, { t: "fn", v: "then" }, { t: "pun", v: "(r => r." }, { t: "fn", v: "json" }, { t: "pun", v: "())" }] },
  { ln: 13, tokens: [{ t: "pun", v: "      ." }, { t: "fn", v: "then" }, { t: "fn", v: "(setData" }, { t: "pun", v: ");" }] },
  { ln: 14, tokens: [{ t: "pun", v: "  }, []);" }] },
  { ln: 15, tokens: [] },
  { ln: 16, tokens: [{ t: "kw", v: "  return" }, { t: "pun", v: " (" }] },
  { ln: 17, tokens: [{ t: "tag", v: "    <div" }, { t: "atr", v: " className" }, { t: "pun", v: '=' }, { t: "str", v: '"dashboard"' }, { t: "tag", v: ">" }] },
  { ln: 18, tokens: [{ t: "tag", v: "      <h1" }, { t: "tag", v: ">" }, { t: "var", v: "Analytics Dashboard" }, { t: "tag", v: "</h1>" }] },
  { ln: 19, tokens: [{ t: "tag", v: "    </div>" }] },
  { ln: 20, tokens: [{ t: "pun", v: "  );" }] },
  { ln: 21, tokens: [{ t: "pun", v: "}" }] },
];

function CodeTab({ app, activeFile }: { app: any, activeFile: string }) {
  const [content, setContent] = useState("");
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!app?.projectId || !activeFile) return;
    const fetchFile = async () => {
      setLoading(true);
      try {
        const res = await fetch(`/api/project-files?projectId=${app.projectId}&version=${app.version || "v1"}&file=${encodeURIComponent(activeFile)}`);
        const data = await res.json();
        setContent(data.content || "// File not found");
      } catch (err) {
        setContent("// Error loading file");
      }
      setLoading(false);
    };
    fetchFile();
  }, [app?.projectId, app?.version, activeFile]);

  const copy = () => { navigator.clipboard.writeText(content); setCopied(true); setTimeout(() => setCopied(false), 2000); };

  const lines = content.split('\n').map((v, i) => ({ ln: i + 1, v }));

  return (
    <div className="flex flex-col h-full">
      <div className="flex items-center justify-between px-4 py-2 border-b border-white/6 bg-white/2 shrink-0">
        <span className="px-2.5 py-1 rounded-md bg-cyan-500/10 border border-cyan-500/20 text-[11px] text-cyan-400 font-mono">{activeFile}</span>
        <button onClick={copy} className="px-2.5 py-1.5 rounded-lg glass text-[11px] text-slate-400">
          <Copy size={11} className="inline mr-1" />{copied ? "Copied!" : "Copy"}
        </button>
      </div>
      <div className="flex-1 overflow-auto bg-[#020617]">
        {loading ? (
          <div className="p-8 text-xs text-slate-600 animate-pulse">Fetching from source…</div>
        ) : (
          <pre className="terminal-font text-[12px] leading-6 p-4">
            {lines.map((line) => (
              <div key={line.ln} className="flex hover:bg-white/2">
                <span className="w-10 text-right text-slate-700 mr-5 shrink-0">{line.ln}</span>
                <span className="text-slate-300">{line.v}</span>
              </div>
            ))}
          </pre>
        )}
      </div>
    </div>
  );
}

// ─── Files Tab ──────────────────────────────────────────────────────────────
const fileTree = [
  {
    name: "app", isDir: true, open: true, depth: 0, children: [
      { name: "page.tsx", isDir: false, depth: 1, active: true },
      { name: "layout.tsx", isDir: false, depth: 1 },
      { name: "globals.css", isDir: false, depth: 1 },
      {
        name: "api", isDir: true, open: false, depth: 1, children: [
          { name: "metrics/route.ts", isDir: false, depth: 2 },
        ]
      },
    ]
  },
  {
    name: "components", isDir: true, open: true, depth: 0, children: [
      { name: "Dashboard.tsx", isDir: false, depth: 1 },
      { name: "Chart.tsx", isDir: false, depth: 1 },
      { name: "Sidebar.tsx", isDir: false, depth: 1 },
    ]
  },
  { name: "lib", isDir: true, open: false, depth: 0, children: [] },
  { name: "public", isDir: true, open: false, depth: 0, children: [] },
  { name: "package.json", isDir: false, depth: 0 },
  { name: "tsconfig.json", isDir: false, depth: 0 },
];

type FileNode = { name: string; path?: string; isDir: boolean; depth: number; open?: boolean; active?: boolean; children?: FileNode[] };

function FileRow({ node, activeFile, onSelect }: { node: FileNode; activeFile: string; onSelect: (n: string) => void }) {
  const [open, setOpen] = useState(node.open ?? false);
  const isActive = !node.isDir && activeFile === (node.path || node.name);

  return (
    <>
      <button
        onClick={() => node.isDir ? setOpen((v) => !v) : onSelect(node.path || node.name)}
        className={`w-full flex items-center gap-1.5 px-2 py-1 rounded-lg text-[12px] transition-all hover:bg-white/5 ${isActive ? "bg-cyan-500/10 text-cyan-400 border border-cyan-500/20" : "text-slate-400"}`}
        style={{ paddingLeft: `${8 + node.depth * 16}px` }}
      >
        {node.isDir ? (open ? <ChevronDown size={12} className="shrink-0 text-slate-500" /> : <ChevronRight size={12} className="shrink-0 text-slate-500" />) : <File size={12} className="shrink-0 text-slate-600" />}
        <span className="truncate">{node.name}</span>
      </button>
      {node.isDir && open && node.children?.map((child) => (
        <FileRow key={(child.path || child.name) + child.depth} node={child} activeFile={activeFile} onSelect={onSelect} />
      ))}
    </>
  );
}

function FilesTab({ app, onSelect }: { app: any, onSelect: (f: string) => void }) {
  const [active, setActive] = useState("app/page.tsx");
  const tree = app?.blueprint || [];

  const handleSelect = (f: string) => {
    setActive(f);
    onSelect(f);
  };

  return (
    <div className="flex flex-col h-full">
      <div className="px-3 py-2 border-b border-white/6 bg-white/2 shrink-0">
        <span className="text-[11px] text-slate-500 font-semibold uppercase tracking-wider">Explorer</span>
      </div>
      <div className="flex-1 overflow-y-auto p-2 flex flex-col gap-0.5">
        {tree.length > 0 ? (
          tree.map((node: any) => <FileRow key={node.name} node={node} activeFile={active} onSelect={handleSelect} />)
        ) : (
          <div className="p-4 text-[10px] text-slate-700 italic">No files generated yet</div>
        )}
      </div>
    </div>
  );
}

// ─── Logs Tab ───────────────────────────────────────────────────────────────
const logLines = [
  { t: "info", time: "13:31:04", msg: "AutoStack Engine v2.4.1 initialized" },
  { t: "info", time: "13:31:05", msg: "Connecting to Gemini 1.5 Pro API..." },
  { t: "success", time: "13:31:06", msg: "✓ API connection established (142ms)" },
  { t: "info", time: "13:31:06", msg: "Analyzing prompt: 'Build a SaaS dashboard...'" },
  { t: "build", time: "13:31:08", msg: "[PLAN] Architecture: Next.js 14 App Router + Tailwind + Prisma" },
  { t: "build", time: "13:31:09", msg: "[GEN] Generating component tree (12 components)" },
  { t: "build", time: "13:31:12", msg: "[GEN] app/page.tsx — 247 lines" },
  { t: "build", time: "13:31:14", msg: "[GEN] app/layout.tsx — 89 lines" },
  { t: "build", time: "13:31:16", msg: "[GEN] components/Dashboard.tsx — 312 lines" },
  { t: "build", time: "13:31:19", msg: "[GEN] components/Chart.tsx — 198 lines" },
  { t: "build", time: "13:31:22", msg: "[API] Generating /api/metrics route" },
  { t: "build", time: "13:31:24", msg: "[API] Generating /api/auth route" },
  { t: "warn", time: "13:31:26", msg: "⚠ Chart library peer dep mismatch — auto-resolving" },
  { t: "success", time: "13:31:28", msg: "✓ All components generated (28 files)" },
  { t: "info", time: "13:31:30", msg: "[SANDBOX] Spinning up preview environment..." },
  { t: "success", time: "13:31:34", msg: "✓ Sandbox ready at localhost:3001" },
  { t: "success", time: "13:31:34", msg: "✓ Generation complete in 28.4s" },
];

const logColors: Record<string, string> = {
  info: "text-slate-400",
  success: "text-emerald-400",
  warn: "text-amber-400",
  error: "text-red-400",
  build: "text-cyan-400",
};

function LogsTab() {
  return (
    <div className="flex flex-col h-full">
      <div className="flex items-center justify-between px-4 py-2 border-b border-white/6 bg-white/2 shrink-0">
        <span className="text-[11px] text-slate-500 font-semibold uppercase tracking-wider">Terminal Output</span>
        <span className="flex items-center gap-1.5">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
          <span className="text-[10px] text-slate-600">Connected</span>
        </span>
      </div>
      <div className="flex-1 overflow-y-auto p-4 terminal-font">
        <div className="flex flex-col gap-1">
          {logLines.map((l, i) => (
            <div key={i} className="flex items-start gap-3 text-[11px] hover:bg-white/2 px-1 py-0.5 rounded">
              <span className="text-slate-700 shrink-0">{l.time}</span>
              <span className={logColors[l.t] ?? "text-slate-400"}>{l.msg}</span>
            </div>
          ))}
          <div className="flex items-start gap-3 text-[11px] px-1 py-0.5">
            <span className="text-slate-700 shrink-0">13:31:35</span>
            <span className="text-slate-400 cursor">Ready</span>
          </div>
        </div>
      </div>
    </div>
  );
}

function VersionsTab({ app, onSwitch }: { app: any, onSwitch: (v: string) => void }) {
  const versions = app?.versions || [{ v: "v1", label: "Initial build", time: "Just now", current: true }];
  return (
    <div className="flex flex-col h-full">
      <div className="px-4 py-2 border-b border-white/6 bg-white/2 shrink-0">
        <span className="text-[11px] text-slate-500 font-semibold uppercase tracking-wider">Version History</span>
      </div>
      <div className="flex-1 overflow-y-auto p-4">
        <div className="relative flex flex-col gap-0 pl-6">
          <div className="absolute left-2 top-3 bottom-3 w-px bg-white/5" />
          {versions.map((ver: any, i: number) => (
            <motion.div
              key={ver.v}
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              className={`relative mb-6 p-4 rounded-xl border ${ver.current ? "bg-cyan-500/5 border-cyan-500/20" : "bg-white/2 border-white/5 hover:border-white/10"}`}
            >
              <div className={`absolute -left-[21px] top-4 w-3 h-3 rounded-full border-2 ${ver.current ? "bg-cyan-500 border-cyan-400" : "bg-slate-800 border-slate-700"}`} />
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-bold text-slate-200">{ver.v}</span>
                {ver.current ? (
                  <span className="text-[9px] px-1.5 py-0.5 rounded-full bg-cyan-500/20 text-cyan-400">Current</span>
                ) : (
                  <button onClick={() => onSwitch(ver.v)} className="text-[9px] text-cyan-500 hover:underline">Switch</button>
                )}
              </div>
              <p className="text-[11px] text-slate-400 mb-1">{ver.label}</p>
              <p className="text-[10px] text-slate-600">{ver.time}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
}

function DocsTab({ app }: { app: any }) {
  const [downloading, setDownloading] = useState(false);
  const downloadPDF = () => {
    setDownloading(true);
    setTimeout(() => setDownloading(false), 2000);
  };

  return (
    <div className="flex flex-col h-full p-8 overflow-y-auto custom-scrollbar">
      <div className="max-w-2xl mx-auto w-full">
        <div className="flex items-center justify-between mb-2">
          <h2 className="text-2xl font-bold text-slate-100">Project Documentation</h2>
          <button 
            onClick={downloadPDF}
            className="flex items-center gap-2 px-4 py-2 rounded-xl bg-cyan-500/10 border border-cyan-500/20 text-[11px] font-bold text-cyan-400 hover:bg-cyan-500/20 transition-all"
          >
            <Download size={14} />
            {downloading ? "Generating PDF..." : "Export as PDF"}
          </button>
        </div>
        <p className="text-slate-500 mb-8 pb-8 border-b border-white/5">Auto-generated technical overview based on your prompt.</p>
        
        <div className="space-y-10">
          <section>
            <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-widest mb-4">Project Summary</h3>
            <p className="text-sm text-slate-400 leading-relaxed italic">
              "{app?.docs?.summary || "No summary available."}"
            </p>
          </section>

          <section>
            <h3 className="text-sm font-bold text-purple-400 uppercase tracking-widest mb-4">Technical Stack</h3>
            <p className="text-sm text-slate-400 leading-relaxed">
              {app?.docs?.architecture || "Next.js 14 + Tailwind CSS"}
            </p>
          </section>

          <section>
            <h3 className="text-sm font-bold text-slate-200 mb-4 tracking-widest">Key Features</h3>
            <ul className="grid grid-cols-2 gap-4">
              {(app?.docs?.features || []).map((f: string) => (
                <li key={f} className="flex items-center gap-2 text-xs text-slate-500">
                  <div className="w-1.5 h-1.5 rounded-full bg-cyan-500/40" />
                  {f}
                </li>
              ))}
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
}

// ─── Main IDEPanel ───────────────────────────────────────────────────────────
export default function IDEPanel({ app, isGenerating, error, onComplete }: { app: any, isGenerating: boolean, error?: string | null, onComplete: () => void }) {
  const [activeTab, setActiveTab] = useState<TabId>("preview");
  const [activeFile, setActiveFile] = useState("app/page.tsx");
  const [currentApp, setCurrentApp] = useState(app);

  useEffect(() => {
    setCurrentApp(app);
  }, [app]);

  useEffect(() => {
    if (isGenerating) setActiveTab("preview");
  }, [isGenerating]);

  const handleVersionSwitch = (v: string) => {
    // In a real app, you'd fetch the new version data here
    setCurrentApp({ ...currentApp, version: v });
  };

  const tabContent: Record<TabId, React.ReactNode> = {
    preview: error ? (
      <div className="h-full flex items-center justify-center text-center p-8">
        <div className="max-w-sm">
          <AlertCircle size={40} className="text-red-500 mx-auto mb-4" />
          <h3 className="text-lg font-bold text-slate-100 mb-2">Generation Failed</h3>
          <p className="text-sm text-slate-500 mb-6">{error}</p>
          <button onClick={() => window.location.reload()} className="px-6 py-2 rounded-xl bg-white/5 border border-white/10 text-sm text-slate-300">Try Again</button>
        </div>
      </div>
    ) : (
      <PreviewTab app={currentApp} isGenerating={isGenerating} onComplete={onComplete} />
    ),
    code: <CodeTab app={currentApp} activeFile={activeFile} />,
    files: <FilesTab app={currentApp} onSelect={(f) => { setActiveFile(f); setActiveTab("code"); }} />,
    logs: <LogsTab />,
    versions: <VersionsTab app={currentApp} onSwitch={handleVersionSwitch} />,
    docs: <DocsTab app={currentApp} />,
    chat: (
      <div className="flex flex-col h-full items-center justify-center text-center p-8">
        <div className="w-16 h-16 rounded-2xl bg-cyan-500/10 flex items-center justify-center mb-4">
          <MessageSquare size={32} className="text-cyan-400" />
        </div>
        <h3 className="text-lg font-bold text-slate-100">AI Chat Assistant</h3>
        <p className="text-sm text-slate-500 max-w-xs mx-auto mb-6">
          Soon you'll be able to edit your code by simply chatting with AutoStack.
        </p>
        <div className="w-full max-w-md glass rounded-xl border border-white/5 p-2 flex items-center gap-2 opacity-50">
          <div className="flex-1 text-[12px] text-slate-600 px-2 text-left">Ask AI to make changes...</div>
          <div className="p-2 rounded-lg bg-white/5 text-slate-700"><Send size={14} /></div>
        </div>
      </div>
    ),
  };

  return (
    <div className="flex flex-col h-full glass border border-white/[0.07] rounded-2xl overflow-hidden">
      <div className="flex items-center justify-between px-3 py-2 border-b border-white/6 bg-white/2 shrink-0">
        <div className="flex items-center gap-1">
          {TABS.map(({ id, icon: Icon, label }) => (
            <button
              key={id}
              id={`tab-${id}`}
              onClick={() => setActiveTab(id)}
              className={`relative flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-[12px] font-medium transition-all duration-200 ${activeTab === id
                ? "bg-linear-to-r from-cyan-500/15 to-purple-600/10 text-slate-100 border border-cyan-500/20"
                : "text-slate-500 hover:text-slate-300 hover:bg-white/4"
                }`}
            >
              <Icon size={13} className={activeTab === id ? "text-cyan-400" : ""} />
              {label}
              {activeTab === id && <motion.span layoutId="activeTab" className="absolute bottom-0 left-1/2 -translate-x-1/2 w-6 h-px bg-linear-to-r from-cyan-500 to-purple-600 rounded-full" />}
            </button>
          ))}
        </div>

        <div className="flex items-center gap-2">
          {app?.zipPath && (
            <a href={app.zipPath} download className="flex items-center gap-2 px-3 py-1.5 rounded-xl bg-white/5 border border-white/10 text-[11px] font-bold text-slate-400 hover:text-white hover:bg-white/8 transition-all">
              <Archive size={14} />
              Export ZIP
            </a>
          )}
        </div>
      </div>

      {/* Tab content */}
      <div className="flex-1 overflow-hidden relative">
        <AnimatePresence mode="wait">
          <motion.div
            key={activeTab}
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -6 }}
            transition={{ duration: 0.2, ease: "easeOut" }}
            className="absolute inset-0 overflow-hidden"
          >
            {tabContent[activeTab]}
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  );
}
